# -*- coding: utf-8 -*-
"""Machine Learning Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cHC878ddIiC-4cFIkp_tSAfAnrra0K35

**IMPORTING ALL IMPORTANT LIBRARIES**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,recall_score,precision_score,r2_score
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

"""**LOADING THE DATASET**"""

data=pd.read_csv("/content/diabetes (1).csv")

data.head(10)

data.info()

data.columns

"""**DATA PREPROCESSING**"""

zero_cols=['Glucose','BloodPressure','SkinThickness','Insulin','BMI']
for col in zero_cols:
  X[col]=X[col].replace(0,X[col].median())

"""**CHECKING NULL VALUES**"""

data.isnull().sum()

data.isnull().all()

data.isnull().any()

"""**EXPLORATORY DATA ANALYSIS (EDA)**"""

fig=sns.heatmap(data.corr(),annot=True,cmap='coolwarm')
fig.figure.set_size_inches(10,10)
fig

data.hist(figsize=(10,8))
plt.show()

sns.boxplot(x='Outcome', y='BMI', data=data)

"""**TRAINING AND TESTING OF DATA**"""

X = data.drop('Outcome', axis=1)
y = data['Outcome']

x_test,x_train,y_test,y_train=train_test_split(X,y,test_size=0.2,random_state=42)

"""**MODEL SELECTION**

**LOGISTIC REGRESSION**
"""

model=LogisticRegression()

"""**STANDARDIZATION**"""

scalar=StandardScaler()
X_train = scalar.fit_transform(x_train)
X_test = scalar.transform(x_test)

model = LogisticRegression(max_iter=500, random_state=42)

"""**MDDEL TRAINING**"""

model.fit(X_train,y_train)

Y_pred=model.predict(X_test)

"""**MODEL EVALUATION**"""

accuracy=accuracy_score(y_test,Y_pred)
accuracy

confusion_matrix(y_test,Y_pred)

recall=recall_score(y_test,Y_pred)
recall

precision=precision_score(y_test,Y_pred)
precision

Report=classification_report(y_test,Y_pred)

print(Report)

"""**SUPPORT VECTOR CLASSIFIER**"""

model1=SVC()

"""**MDDEL TRAINING**"""

model1.fit(X_train,y_train)

Y_pred=model1.predict(X_test)

"""**MODEL EVALUATION**"""

accuracy1=accuracy_score(y_test,Y_pred)
accuracy1

precision1=precision_score(y_test,Y_pred)
precision1

recall1=recall_score(y_test,Y_pred)
recall1

Report1=classification_report(y_test,Y_pred)

print(Report1)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, Y_pred)
print(cm)

"""**NAIVE BAYES**"""

model2=GaussianNB()

"""**MDDEL TRAINING**"""

model2.fit(X_train,y_train)

y_pred=model2.predict(X_test)

"""**MODEL EVALUATION**"""

accuracy2=accuracy_score(y_test,y_pred)
accuracy2

precision2=precision_score(y_test,y_pred)
precision2

recall2=recall_score(y_test,y_pred)
recall2

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

"""**DECISION TREE CLASSIFIER**"""

model3=DecisionTreeClassifier()

"""**MDDEL TRAINING**"""

model3.fit(X_train,y_train)

y1_pred=model3.predict(X_test)

"""**MODEL EVALUATION**"""

accuracy3=accuracy_score(y_test,y1_pred)
accuracy3

precision3=precision_score(y_test,y1_pred)
print (precision3)

recall3=recall_score(y_test,y1_pred)
recall3

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y1_pred)
print(cm)

"""**COMPARISON OF MODEL ACCURACY**"""

plt.figure(figsize=(12,6))
accuracy_scores = [accuracy, accuracy1, accuracy2, accuracy3]
models = ['Logistic Regression', 'SVC','Naive Bayes','Decison Tree Classifier']
plt.bar(models, accuracy_scores)
plt.ylabel('Accuracy')
plt.title('Comparison of Model Accuracy')
plt.show()

"""**PRECISION VS RECALL COMAPRISON**"""

import matplotlib.pyplot as plt
import numpy as np

# Models
models = ['Logistic Regression', 'SVC', 'Naive Bayes', 'Decision Tree Classifier']

# Precision and Recall values for each model (floats)
precision_values = [precision, precision1, precision2, precision3]
recall_values = [recall, recall1, recall2, recall3]

# X-axis positions
x = np.arange(len(models))
width = 0.35  # width of bars

# Create grouped bars
plt.bar(x - width/2, precision_values, width, label='Precision', color='skyblue')
plt.bar(x + width/2, recall_values, width, label='Recall', color='salmon')

# Labels, title, and ticks
plt.xlabel('Models')
plt.ylabel('Score')
plt.title('Precision vs Recall Comparison')
plt.xticks(x, models, rotation=10)
plt.legend()

# Add value labels above bars
for i in range(len(models)):
    plt.text(x[i] - width/2, precision_values[i] + 0.01, f"{precision_values[i]:.2f}", ha='center', fontsize=9)
    plt.text(x[i] + width/2, recall_values[i] + 0.01, f"{recall_values[i]:.2f}", ha='center', fontsize=9)

plt.tight_layout()
plt.show()

